spring:
  application:
    name: SubService

server:
  port: 8082
  address: 0.0.0.0

kafka:
  bootstrapAddress: kafka:9092

message:
  topic:
    name: messageTopic
    numberOfPartitions: 2
    replicationFactor: 1
