version: '2'
services:
  pubservice:
    image: briansjavablog/pub-service:latest
    ports:
      - "8082:8082"
  subservice:
    image: briansjavablog/sub-service:latest
    ports:
      - "8083:8083"
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.17.0.1
      # running outside of docker-compose
      #KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      # running with docker-compose
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CREATE_TOPICS: "logs:1:1,messageTopic:2:1,messageDeadLetterTopic:2:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
